language: python
branches:
  only:
  - master
  - travis-ci_integration
script:
- echo "skipping tests"
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: "Insek1v29RRloKkM/MXTP0hyQ9J4NrXxE9CpZU9vnBW0olMw2YbzktTT7m1ktbzz+230aBXPXB+YfMoQxWRHbJHWDDG//mVul5p5K6NsS5ONAgOUl4UBFUSakcApF2es4WKo0Q4nNk5jKgO1qK7xQQOt9v6U0UTuk+DagX4yTlpV1XRxLJF3nS//kps0bDXPe7ZTtk44vNjC+HquZpnHoe9dTdrJvJluTu7lilXTh0nPLqMHO3iHu1FFbpjynZ55y1eJ2hPVqIgmAwWsEaOzyXpqR6R3lq7FFgQxRbG1QWNwHY3aenQ5e5sZWySWkaoEavIIKCsrmuo5pEXq8wN3it2ePEruJsrNAshyo1+UvyvxZ6Dfavt6uW5CcprPmA0YLXY6qZnDkhZkL67/w98HjYvCwC2cV+EmG8I4Ley/Fk2ql512VKY+L83QsmSdQrywaeJj1N59FQGYZZPRvP+awTivDdIP/pTjhpjcZ6qXfXS8JFzvpe5qGBSpl7FmRj7yfwQAPa5D1Ir0JZhZIF92Fy5bBUBqhGyJpVnbkq0gms9KELbtbSzfT/2lhfKSvSEuZjLflJVHmNd97q2x9XlKUu4qpKruLbiGbgCwrg30TvcJ9JkH1beXhrjCYiht9iPIxpGqM5OaunbMx+2DZVx6g/I6j27jscM0VKTTCH7DGzY="
    skip_existing: true
    on:
      branch: master

  - provider: pypi
    user: "__token__"
    password:
      secure: "Insek1v29RRloKkM/MXTP0hyQ9J4NrXxE9CpZU9vnBW0olMw2YbzktTT7m1ktbzz+230aBXPXB+YfMoQxWRHbJHWDDG//mVul5p5K6NsS5ONAgOUl4UBFUSakcApF2es4WKo0Q4nNk5jKgO1qK7xQQOt9v6U0UTuk+DagX4yTlpV1XRxLJF3nS//kps0bDXPe7ZTtk44vNjC+HquZpnHoe9dTdrJvJluTu7lilXTh0nPLqMHO3iHu1FFbpjynZ55y1eJ2hPVqIgmAwWsEaOzyXpqR6R3lq7FFgQxRbG1QWNwHY3aenQ5e5sZWySWkaoEavIIKCsrmuo5pEXq8wN3it2ePEruJsrNAshyo1+UvyvxZ6Dfavt6uW5CcprPmA0YLXY6qZnDkhZkL67/w98HjYvCwC2cV+EmG8I4Ley/Fk2ql512VKY+L83QsmSdQrywaeJj1N59FQGYZZPRvP+awTivDdIP/pTjhpjcZ6qXfXS8JFzvpe5qGBSpl7FmRj7yfwQAPa5D1Ir0JZhZIF92Fy5bBUBqhGyJpVnbkq0gms9KELbtbSzfT/2lhfKSvSEuZjLflJVHmNd97q2x9XlKUu4qpKruLbiGbgCwrg30TvcJ9JkH1beXhrjCYiht9iPIxpGqM5OaunbMx+2DZVx6g/I6j27jscM0VKTTCH7DGzY="
    skip_existing: true
    on:
      branch: travis-ci_integration